// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package circuits

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/huazhihao/go-netbox/models"
)

// NewCircuitsCustomermanagersUpdateParams creates a new CircuitsCustomermanagersUpdateParams object
// with the default values initialized.
func NewCircuitsCustomermanagersUpdateParams() *CircuitsCustomermanagersUpdateParams {
	var ()
	return &CircuitsCustomermanagersUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCircuitsCustomermanagersUpdateParamsWithTimeout creates a new CircuitsCustomermanagersUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCircuitsCustomermanagersUpdateParamsWithTimeout(timeout time.Duration) *CircuitsCustomermanagersUpdateParams {
	var ()
	return &CircuitsCustomermanagersUpdateParams{

		timeout: timeout,
	}
}

// NewCircuitsCustomermanagersUpdateParamsWithContext creates a new CircuitsCustomermanagersUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewCircuitsCustomermanagersUpdateParamsWithContext(ctx context.Context) *CircuitsCustomermanagersUpdateParams {
	var ()
	return &CircuitsCustomermanagersUpdateParams{

		Context: ctx,
	}
}

// NewCircuitsCustomermanagersUpdateParamsWithHTTPClient creates a new CircuitsCustomermanagersUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCircuitsCustomermanagersUpdateParamsWithHTTPClient(client *http.Client) *CircuitsCustomermanagersUpdateParams {
	var ()
	return &CircuitsCustomermanagersUpdateParams{
		HTTPClient: client,
	}
}

/*CircuitsCustomermanagersUpdateParams contains all the parameters to send to the API endpoint
for the circuits customermanagers update operation typically these are written to a http.Request
*/
type CircuitsCustomermanagersUpdateParams struct {

	/*Data*/
	Data *models.CustomerManager
	/*ID
	  A unique integer value identifying this customer manager.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) WithTimeout(timeout time.Duration) *CircuitsCustomermanagersUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) WithContext(ctx context.Context) *CircuitsCustomermanagersUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) WithHTTPClient(client *http.Client) *CircuitsCustomermanagersUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) WithData(data *models.CustomerManager) *CircuitsCustomermanagersUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) SetData(data *models.CustomerManager) {
	o.Data = data
}

// WithID adds the id to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) WithID(id int64) *CircuitsCustomermanagersUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the circuits customermanagers update params
func (o *CircuitsCustomermanagersUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CircuitsCustomermanagersUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
