// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/huazhihao/go-netbox/models"
)

// NewDcimDeviceDepartmentsPartialUpdateParams creates a new DcimDeviceDepartmentsPartialUpdateParams object
// with the default values initialized.
func NewDcimDeviceDepartmentsPartialUpdateParams() *DcimDeviceDepartmentsPartialUpdateParams {
	var ()
	return &DcimDeviceDepartmentsPartialUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimDeviceDepartmentsPartialUpdateParamsWithTimeout creates a new DcimDeviceDepartmentsPartialUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimDeviceDepartmentsPartialUpdateParamsWithTimeout(timeout time.Duration) *DcimDeviceDepartmentsPartialUpdateParams {
	var ()
	return &DcimDeviceDepartmentsPartialUpdateParams{

		timeout: timeout,
	}
}

// NewDcimDeviceDepartmentsPartialUpdateParamsWithContext creates a new DcimDeviceDepartmentsPartialUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimDeviceDepartmentsPartialUpdateParamsWithContext(ctx context.Context) *DcimDeviceDepartmentsPartialUpdateParams {
	var ()
	return &DcimDeviceDepartmentsPartialUpdateParams{

		Context: ctx,
	}
}

// NewDcimDeviceDepartmentsPartialUpdateParamsWithHTTPClient creates a new DcimDeviceDepartmentsPartialUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimDeviceDepartmentsPartialUpdateParamsWithHTTPClient(client *http.Client) *DcimDeviceDepartmentsPartialUpdateParams {
	var ()
	return &DcimDeviceDepartmentsPartialUpdateParams{
		HTTPClient: client,
	}
}

/*DcimDeviceDepartmentsPartialUpdateParams contains all the parameters to send to the API endpoint
for the dcim device departments partial update operation typically these are written to a http.Request
*/
type DcimDeviceDepartmentsPartialUpdateParams struct {

	/*Data*/
	Data *models.DeviceDepartment
	/*ID
	  A unique integer value identifying this device department.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) WithTimeout(timeout time.Duration) *DcimDeviceDepartmentsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) WithContext(ctx context.Context) *DcimDeviceDepartmentsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) WithHTTPClient(client *http.Client) *DcimDeviceDepartmentsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) WithData(data *models.DeviceDepartment) *DcimDeviceDepartmentsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) SetData(data *models.DeviceDepartment) {
	o.Data = data
}

// WithID adds the id to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) WithID(id int64) *DcimDeviceDepartmentsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim device departments partial update params
func (o *DcimDeviceDepartmentsPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DcimDeviceDepartmentsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
