// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/huazhihao/go-netbox/models"
)

// NewDcimDeviceDepartmentsCreateParams creates a new DcimDeviceDepartmentsCreateParams object
// with the default values initialized.
func NewDcimDeviceDepartmentsCreateParams() *DcimDeviceDepartmentsCreateParams {
	var ()
	return &DcimDeviceDepartmentsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimDeviceDepartmentsCreateParamsWithTimeout creates a new DcimDeviceDepartmentsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimDeviceDepartmentsCreateParamsWithTimeout(timeout time.Duration) *DcimDeviceDepartmentsCreateParams {
	var ()
	return &DcimDeviceDepartmentsCreateParams{

		timeout: timeout,
	}
}

// NewDcimDeviceDepartmentsCreateParamsWithContext creates a new DcimDeviceDepartmentsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimDeviceDepartmentsCreateParamsWithContext(ctx context.Context) *DcimDeviceDepartmentsCreateParams {
	var ()
	return &DcimDeviceDepartmentsCreateParams{

		Context: ctx,
	}
}

// NewDcimDeviceDepartmentsCreateParamsWithHTTPClient creates a new DcimDeviceDepartmentsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimDeviceDepartmentsCreateParamsWithHTTPClient(client *http.Client) *DcimDeviceDepartmentsCreateParams {
	var ()
	return &DcimDeviceDepartmentsCreateParams{
		HTTPClient: client,
	}
}

/*DcimDeviceDepartmentsCreateParams contains all the parameters to send to the API endpoint
for the dcim device departments create operation typically these are written to a http.Request
*/
type DcimDeviceDepartmentsCreateParams struct {

	/*Data*/
	Data *models.DeviceDepartment

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) WithTimeout(timeout time.Duration) *DcimDeviceDepartmentsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) WithContext(ctx context.Context) *DcimDeviceDepartmentsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) WithHTTPClient(client *http.Client) *DcimDeviceDepartmentsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) WithData(data *models.DeviceDepartment) *DcimDeviceDepartmentsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim device departments create params
func (o *DcimDeviceDepartmentsCreateParams) SetData(data *models.DeviceDepartment) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *DcimDeviceDepartmentsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
