// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDcimSiteownersReadParams creates a new DcimSiteownersReadParams object
// with the default values initialized.
func NewDcimSiteownersReadParams() *DcimSiteownersReadParams {
	var ()
	return &DcimSiteownersReadParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDcimSiteownersReadParamsWithTimeout creates a new DcimSiteownersReadParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDcimSiteownersReadParamsWithTimeout(timeout time.Duration) *DcimSiteownersReadParams {
	var ()
	return &DcimSiteownersReadParams{

		timeout: timeout,
	}
}

// NewDcimSiteownersReadParamsWithContext creates a new DcimSiteownersReadParams object
// with the default values initialized, and the ability to set a context for a request
func NewDcimSiteownersReadParamsWithContext(ctx context.Context) *DcimSiteownersReadParams {
	var ()
	return &DcimSiteownersReadParams{

		Context: ctx,
	}
}

// NewDcimSiteownersReadParamsWithHTTPClient creates a new DcimSiteownersReadParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDcimSiteownersReadParamsWithHTTPClient(client *http.Client) *DcimSiteownersReadParams {
	var ()
	return &DcimSiteownersReadParams{
		HTTPClient: client,
	}
}

/*DcimSiteownersReadParams contains all the parameters to send to the API endpoint
for the dcim siteowners read operation typically these are written to a http.Request
*/
type DcimSiteownersReadParams struct {

	/*ID
	  A unique integer value identifying this siteowner.

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the dcim siteowners read params
func (o *DcimSiteownersReadParams) WithTimeout(timeout time.Duration) *DcimSiteownersReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim siteowners read params
func (o *DcimSiteownersReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim siteowners read params
func (o *DcimSiteownersReadParams) WithContext(ctx context.Context) *DcimSiteownersReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim siteowners read params
func (o *DcimSiteownersReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim siteowners read params
func (o *DcimSiteownersReadParams) WithHTTPClient(client *http.Client) *DcimSiteownersReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim siteowners read params
func (o *DcimSiteownersReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim siteowners read params
func (o *DcimSiteownersReadParams) WithID(id int64) *DcimSiteownersReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim siteowners read params
func (o *DcimSiteownersReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DcimSiteownersReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
