// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package extras

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/huazhihao/go-netbox/models"
)

// NewExtrasApprovallistsCreateParams creates a new ExtrasApprovallistsCreateParams object
// with the default values initialized.
func NewExtrasApprovallistsCreateParams() *ExtrasApprovallistsCreateParams {
	var ()
	return &ExtrasApprovallistsCreateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExtrasApprovallistsCreateParamsWithTimeout creates a new ExtrasApprovallistsCreateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExtrasApprovallistsCreateParamsWithTimeout(timeout time.Duration) *ExtrasApprovallistsCreateParams {
	var ()
	return &ExtrasApprovallistsCreateParams{

		timeout: timeout,
	}
}

// NewExtrasApprovallistsCreateParamsWithContext creates a new ExtrasApprovallistsCreateParams object
// with the default values initialized, and the ability to set a context for a request
func NewExtrasApprovallistsCreateParamsWithContext(ctx context.Context) *ExtrasApprovallistsCreateParams {
	var ()
	return &ExtrasApprovallistsCreateParams{

		Context: ctx,
	}
}

// NewExtrasApprovallistsCreateParamsWithHTTPClient creates a new ExtrasApprovallistsCreateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExtrasApprovallistsCreateParamsWithHTTPClient(client *http.Client) *ExtrasApprovallistsCreateParams {
	var ()
	return &ExtrasApprovallistsCreateParams{
		HTTPClient: client,
	}
}

/*ExtrasApprovallistsCreateParams contains all the parameters to send to the API endpoint
for the extras approvallists create operation typically these are written to a http.Request
*/
type ExtrasApprovallistsCreateParams struct {

	/*Data*/
	Data *models.ApprovalList

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) WithTimeout(timeout time.Duration) *ExtrasApprovallistsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) WithContext(ctx context.Context) *ExtrasApprovallistsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) WithHTTPClient(client *http.Client) *ExtrasApprovallistsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) WithData(data *models.ApprovalList) *ExtrasApprovallistsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the extras approvallists create params
func (o *ExtrasApprovallistsCreateParams) SetData(data *models.ApprovalList) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *ExtrasApprovallistsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
